-- delete database and create new one
DROP DATABASE IF EXISTS wishlist;
CREATE DATABASE wishlist;

USE wishlist;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS wishes;
CREATE TABLE wishes (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
price VARCHAR(45) NOT NULL,
url VARCHAR(300),
user_id INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users(id)
);